"""
assembler.py - Binary Fragment Reassembly & Integrity Verification Engine

Reconstructs original file byte streams from custom-header tagged binary fragments
generated by fragmenter.py. Performs File ID validation, missing fragment index detection,
and payload concatenation.

Author: Cypher Engineering Team
"""

from __future__ import annotations

import logging
import os
import struct
import sys
from dataclasses import dataclass
from typing import Dict, List, Optional, Set, Tuple, Union

# Ensure backend directory is present in sys.path
_backend_dir = os.path.dirname(os.path.abspath(__file__))
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

# Module logger
logger = logging.getLogger(__name__)

# Header Constants (Matching fragmenter.py specification)
FRAGMENT_MAGIC: bytes = b"FRG\x00"  # 4-byte custom magic identifier
HEADER_FORMAT: str = ">4s4sII"      # Magic (4B), File ID (4B), Chunk Index (4B), Total Chunks (4B)
HEADER_SIZE: int = struct.calcsize(HEADER_FORMAT)  # 16 bytes


# ═══════════════════════════════════════════════════════════════════════════
# Custom Exception Hierarchy
# ═══════════════════════════════════════════════════════════════════════════

class AssemblerError(Exception):
    """Base exception for assembler operations."""
    pass


class InvalidFragmentError(AssemblerError, ValueError):
    """Raised when a fragment buffer or binary header is malformed."""
    pass


class MissingFragmentError(AssemblerError, ValueError):
    """Raised when one or more fragment indices are missing from the collection."""
    pass


class MismatchedFileIDError(AssemblerError, ValueError):
    """Raised when fragments belong to different File IDs."""
    pass


# ═══════════════════════════════════════════════════════════════════════════
# Fragment Header Parser & Validator
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class ParsedFragment:
    """Internal container for parsed fragment metadata and payload."""
    file_id: bytes
    chunk_index: int
    total_chunks: int
    payload: bytes


def parse_fragment_header(
    fragment: Union[bytes, bytearray, memoryview],
    index_hint: int = 0
) -> Tuple[bytes, int, int, bytes]:
    """
    Parses and validates the 16-byte custom header of a single binary fragment.

    Args:
        fragment: Fragment byte buffer.
        index_hint: List index for error diagnostic reporting.

    Returns:
        Tuple of (File ID, Chunk Index, Total Chunks, Raw Payload Bytes).

    Raises:
        InvalidFragmentError: If header is too short or magic signature is invalid.
    """
    if not isinstance(fragment, (bytes, bytearray, memoryview)):
        raise InvalidFragmentError(
            f"Fragment at list index {index_hint} is not a bytes-like object, "
            f"got {type(fragment).__name__}."
        )

    byte_data = bytes(fragment)
    if len(byte_data) < HEADER_SIZE:
        raise InvalidFragmentError(
            f"Fragment at list index {index_hint} length ({len(byte_data)} bytes) "
            f"is smaller than required header size ({HEADER_SIZE} bytes)."
        )

    magic, file_id, chunk_idx, total_chunks = struct.unpack(HEADER_FORMAT, byte_data[:HEADER_SIZE])

    if magic != FRAGMENT_MAGIC:
        raise InvalidFragmentError(
            f"Fragment at list index {index_hint} has invalid magic header {magic!r}, "
            f"expected {FRAGMENT_MAGIC!r}."
        )

    if total_chunks < 1:
        raise InvalidFragmentError(
            f"Fragment at list index {index_hint} specifies invalid total_chunks count: {total_chunks}."
        )

    if chunk_idx >= total_chunks:
        raise InvalidFragmentError(
            f"Fragment at list index {index_hint} has chunk_index {chunk_idx} "
            f"which exceeds total_chunks ({total_chunks})."
        )

    payload = byte_data[HEADER_SIZE:]
    return file_id, chunk_idx, total_chunks, payload


# ═══════════════════════════════════════════════════════════════════════════
# Main Assembly Public API
# ═══════════════════════════════════════════════════════════════════════════

def assemble_fragments(
    fragments: List[Union[bytes, bytearray, memoryview]]
) -> bytes:
    """
    Reconstructs an original byte stream from a list of header-tagged binary fragments.

    Validation Workflow:
      1. Parses the 16-byte custom 'FRG\\x00' header of each fragment.
      2. Validates that ALL fragments share the exact same 4-byte File ID.
      3. Verifies that no chunk indices are missing from 0 to (total_chunks - 1).
      4. Sorts fragments by chunk index, strips the headers, and concatenates payloads.

    Args:
        fragments: Collection of binary fragment byte streams.

    Returns:
        Reconstructed raw file byte stream (bytes).

    Raises:
        InvalidFragmentError: If fragments are malformed, empty, or contain duplicate indices.
        MismatchedFileIDError: If fragments from different File IDs are mixed.
        MissingFragmentError: If one or more chunk indices are missing.
    """
    if not isinstance(fragments, (list, tuple)):
        raise InvalidFragmentError(f"Expected list of fragments, got {type(fragments).__name__}.")

    if not fragments:
        raise InvalidFragmentError("Fragment list cannot be empty.")

    parsed_items: List[Tuple[int, bytes]] = []
    expected_file_id: Optional[bytes] = None
    expected_total_chunks: Optional[int] = None
    seen_indices: Set[int] = set()

    for idx, frag in enumerate(fragments):
        file_id, chunk_idx, total_chunks, payload = parse_fragment_header(frag, index_hint=idx)

        # 1. File ID Consistency Check
        if expected_file_id is None:
            expected_file_id = file_id
            expected_total_chunks = total_chunks
        else:
            if file_id != expected_file_id:
                raise MismatchedFileIDError(
                    f"Mismatched File ID in fragment list: expected {expected_file_id.hex()}, "
                    f"got {file_id.hex()} at list index {idx}."
                )

            if total_chunks != expected_total_chunks:
                raise InvalidFragmentError(
                    f"Mismatched total_chunks count: expected {expected_total_chunks}, "
                    f"got {total_chunks} at list index {idx}."
                )

        # 2. Duplicate Index Check
        if chunk_idx in seen_indices:
            raise InvalidFragmentError(
                f"Duplicate fragment index {chunk_idx} detected for File ID {file_id.hex()}."
            )
        seen_indices.add(chunk_idx)

        parsed_items.append((chunk_idx, payload))

    # 3. Missing Fragment Index Check
    total_required = expected_total_chunks or 0
    required_indices = set(range(total_required))
    missing_indices = sorted(list(required_indices - seen_indices))

    if missing_indices:
        missing_str = ", ".join(map(str, missing_indices))
        raise MissingFragmentError(
            f"Missing {len(missing_indices)} fragment(s) for File ID {expected_file_id.hex() if expected_file_id else 'unknown'}: "
            f"missing indices [{missing_str}] out of {total_required} expected total chunks."
        )

    # 4. Sort by Chunk Index & Concatenate Payloads
    parsed_items.sort(key=lambda item: item[0])
    assembled_bytes = b"".join(payload for _, payload in parsed_items)

    logger.debug(
        "Successfully assembled %d fragments into %d bytes (File ID: %s)",
        len(parsed_items), len(assembled_bytes), expected_file_id.hex() if expected_file_id else "N/A"
    )

    return assembled_bytes


# Convenient alias matching standard module naming
assemble_file = assemble_fragments
reassemble_file = assemble_fragments
